### ISSUE TITLE
创建的规则怎么在nacos看不到啊

### ISSUE THREAD

**Issue by Phoebus888** [diwenzheng/Sentinel-nacos#1]
如题

**Comment by diwenzheng** [comment]
要配置环境变量 肯定可以 @Phoebus888

**Comment by Phoebus888** [comment]
#连接地址(localhost:8848)
NACOS_ENDPOINT
#命名空间(prod)
NACOS_NAMESPACE
#账户(nacos)
NACOS_USERNAME
#密码(nacos)
NACOS_PASSWORD
这些看到了     数据库里面有配置   页面上没有  nacos版本是1.4.2    

sentinel是正常使用的

**Comment by diwenzheng** [comment]
> 

如果你是run的jar包,通过设置环境变量即可呀,如果是docker运行,直接在环境变量那里加上就可以
